// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Specification.EFCore;

#nullable disable

namespace Specification.Migrations
{
    [DbContext(typeof(SpecPatternContext))]
    [Migration("20240306190959_UpdatedDirectorAndMovieEntities")]
    partial class UpdatedDirectorAndMovieEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Specification.EFCore.Director", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Director");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a243074-15ab-4604-bb7e-93143b4b832f"),
                            Name = "Marc Webb"
                        },
                        new
                        {
                            Id = new Guid("fcf543cc-906b-4c2e-95a7-59afac0fb95c"),
                            Name = "Bill Condon"
                        },
                        new
                        {
                            Id = new Guid("1dad05db-c673-4b61-b1ae-345f467758b7"),
                            Name = "Chris Renaud"
                        },
                        new
                        {
                            Id = new Guid("944bab78-7b62-434d-a028-9cdcf79134c9"),
                            Name = "Jon Favreau"
                        },
                        new
                        {
                            Id = new Guid("ba5186f1-a6c8-4209-98fa-be0453d0be11"),
                            Name = "M. Night Shyamalan"
                        },
                        new
                        {
                            Id = new Guid("951b7249-3254-4678-ad34-140573845836"),
                            Name = "Alex Kurtzman"
                        });
                });

            modelBuilder.Entity("Specification.EFCore.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MpaaRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0146185-dc35-415f-a3c9-adb36db044a8"),
                            DirectorId = new Guid("2a243074-15ab-4604-bb7e-93143b4b832f"),
                            Genre = "Adventure",
                            MpaaRating = 3,
                            Name = "The Amazing Spider-Man",
                            Rating = 7.0,
                            ReleaseDate = new DateTime(2012, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("76361f10-743c-41b5-9618-809cafc8473d"),
                            DirectorId = new Guid("fcf543cc-906b-4c2e-95a7-59afac0fb95c"),
                            Genre = "Family",
                            MpaaRating = 3,
                            Name = "Beauty and the Beast",
                            Rating = 7.7999999999999998,
                            ReleaseDate = new DateTime(2017, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("441a245f-53e5-4aae-83bc-3523fdbd1555"),
                            DirectorId = new Guid("1dad05db-c673-4b61-b1ae-345f467758b7"),
                            Genre = "Adventure",
                            MpaaRating = 1,
                            Name = "The Secret Life of Pets",
                            Rating = 6.5999999999999996,
                            ReleaseDate = new DateTime(2016, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e41b3843-2d48-4e6e-8647-aa6142d6d365"),
                            DirectorId = new Guid("944bab78-7b62-434d-a028-9cdcf79134c9"),
                            Genre = "Fantasy",
                            MpaaRating = 2,
                            Name = "The Jungle Book",
                            Rating = 7.5,
                            ReleaseDate = new DateTime(2016, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7c959ced-5328-4a55-8d40-5b949e638471"),
                            DirectorId = new Guid("ba5186f1-a6c8-4209-98fa-be0453d0be11"),
                            Genre = "Horror",
                            MpaaRating = 3,
                            Name = "Split",
                            Rating = 7.4000000000000004,
                            ReleaseDate = new DateTime(2017, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1cb8a619-f422-4693-8482-8b5c5878ba02"),
                            DirectorId = new Guid("951b7249-3254-4678-ad34-140573845836"),
                            Genre = "Action",
                            MpaaRating = 4,
                            Name = "The Mummy",
                            Rating = 6.7000000000000002,
                            ReleaseDate = new DateTime(2017, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Specification.EFCore.Movie", b =>
                {
                    b.HasOne("Specification.EFCore.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });
#pragma warning restore 612, 618
        }
    }
}
